// MCC (Mobile Country Code) prefix -> country name, derived from IMSI.
export const mccMap = {
  '460': { en: 'China',        zh: '中国' },
  '461': { en: 'China',        zh: '中国' },
  '466': { en: 'Taiwan',       zh: '台湾' },
  '454': { en: 'Hong Kong',    zh: '香港' },
  '455': { en: 'Macau',        zh: '澳门' },
  '440': { en: 'Japan',        zh: '日本' },
  '441': { en: 'Japan',        zh: '日本' },
  '450': { en: 'Korea',        zh: '韩国' },
  '452': { en: 'Vietnam',      zh: '越南' },
  '456': { en: 'Cambodia',     zh: '柬埔寨' },
  '457': { en: 'Laos',         zh: '老挝' },
  '502': { en: 'Malaysia',     zh: '马来西亚' },
  '510': { en: 'Indonesia',    zh: '印度尼西亚' },
  '515': { en: 'Philippines',  zh: '菲律宾' },
  '520': { en: 'Thailand',     zh: '泰国' },
  '525': { en: 'Singapore',    zh: '新加坡' },
  '404': { en: 'India',        zh: '印度' },
  '405': { en: 'India',        zh: '印度' },
  '406': { en: 'India',        zh: '印度' },
  '410': { en: 'Pakistan',     zh: '巴基斯坦' },
  '411': { en: 'Pakistan',     zh: '巴基斯坦' },
  '470': { en: 'Bangladesh',   zh: '孟加拉国' },
  '414': { en: 'Myanmar',      zh: '缅甸' },
  '413': { en: 'Sri Lanka',    zh: '斯里兰卡' },
  '429': { en: 'Nepal',        zh: '尼泊尔' },
  '428': { en: 'Mongolia',     zh: '蒙古' },
  '401': { en: 'Kazakhstan',   zh: '哈萨克斯坦' },
  '434': { en: 'Uzbekistan',   zh: '乌兹别克斯坦' },
  '432': { en: 'Iran',         zh: '伊朗' },
  '418': { en: 'Iraq',         zh: '伊拉克' },
  '425': { en: 'Israel',       zh: '以色列' },
  '416': { en: 'Jordan',       zh: '约旦' },
  '415': { en: 'Lebanon',      zh: '黎巴嫩' },
  '419': { en: 'Kuwait',       zh: '科威特' },
  '426': { en: 'Bahrain',      zh: '巴林' },
  '427': { en: 'Qatar',        zh: '卡塔尔' },
  '420': { en: 'Saudi Arabia', zh: '沙特阿拉伯' },
  '424': { en: 'UAE',          zh: '阿联酋' },
  '430': { en: 'UAE',          zh: '阿联酋' },
  '431': { en: 'UAE',          zh: '阿联酋' },
  '286': { en: 'Turkey',       zh: '土耳其' },
  '250': { en: 'Russia',       zh: '俄罗斯' },
  '255': { en: 'Ukraine',      zh: '乌克兰' },
  '202': { en: 'Greece',       zh: '希腊' },
  '204': { en: 'Netherlands',  zh: '荷兰' },
  '206': { en: 'Belgium',      zh: '比利时' },
  '208': { en: 'France',       zh: '法国' },
  '214': { en: 'Spain',        zh: '西班牙' },
  '216': { en: 'Hungary',      zh: '匈牙利' },
  '218': { en: 'Bosnia',       zh: '波斯尼亚' },
  '219': { en: 'Croatia',      zh: '克罗地亚' },
  '220': { en: 'Serbia',       zh: '塞尔维亚' },
  '222': { en: 'Italy',        zh: '意大利' },
  '226': { en: 'Romania',      zh: '罗马尼亚' },
  '228': { en: 'Switzerland',  zh: '瑞士' },
  '230': { en: 'Czechia',      zh: '捷克' },
  '231': { en: 'Slovakia',     zh: '斯洛伐克' },
  '232': { en: 'Austria',      zh: '奥地利' },
  '234': { en: 'UK',           zh: '英国' },
  '235': { en: 'UK',           zh: '英国' },
  '238': { en: 'Denmark',      zh: '丹麦' },
  '240': { en: 'Sweden',       zh: '瑞典' },
  '242': { en: 'Norway',       zh: '挪威' },
  '244': { en: 'Finland',      zh: '芬兰' },
  '246': { en: 'Lithuania',    zh: '立陶宛' },
  '247': { en: 'Latvia',       zh: '拉脱维亚' },
  '248': { en: 'Estonia',      zh: '爱沙尼亚' },
  '260': { en: 'Poland',       zh: '波兰' },
  '262': { en: 'Germany',      zh: '德国' },
  '268': { en: 'Portugal',     zh: '葡萄牙' },
  '272': { en: 'Ireland',      zh: '爱尔兰' },
  '284': { en: 'Bulgaria',     zh: '保加利亚' },
  '293': { en: 'Slovenia',     zh: '斯洛文尼亚' },
  '302': { en: 'Canada',       zh: '加拿大' },
  '310': { en: 'USA',          zh: '美国' },
  '311': { en: 'USA',          zh: '美国' },
  '312': { en: 'USA',          zh: '美国' },
  '313': { en: 'USA',          zh: '美国' },
  '314': { en: 'USA',          zh: '美国' },
  '315': { en: 'USA',          zh: '美国' },
  '316': { en: 'USA',          zh: '美国' },
  '334': { en: 'Mexico',       zh: '墨西哥' },
  '505': { en: 'Australia',    zh: '澳大利亚' },
  '530': { en: 'New Zealand',  zh: '新西兰' },
  '602': { en: 'Egypt',        zh: '埃及' },
  '603': { en: 'Algeria',      zh: '阿尔及利亚' },
  '604': { en: 'Morocco',      zh: '摩洛哥' },
  '605': { en: 'Tunisia',      zh: '突尼斯' },
  '620': { en: 'Ghana',        zh: '加纳' },
  '621': { en: 'Nigeria',      zh: '尼日利亚' },
  '636': { en: 'Ethiopia',     zh: '埃塞俄比亚' },
  '639': { en: 'Kenya',        zh: '肯尼亚' },
  '640': { en: 'Tanzania',     zh: '坦桑尼亚' },
  '655': { en: 'South Africa', zh: '南非' },
  '722': { en: 'Argentina',    zh: '阿根廷' },
  '724': { en: 'Brazil',       zh: '巴西' },
  '725': { en: 'Brazil',       zh: '巴西' },
  '730': { en: 'Chile',        zh: '智利' },
  '732': { en: 'Colombia',     zh: '哥伦比亚' },
  '733': { en: 'Colombia',     zh: '哥伦比亚' },
};

export function getMccCountry(imsi, langVal) {
  if (!imsi || String(imsi).length < 3) return '—';
  const mcc = String(imsi).slice(0, 3);
  const entry = mccMap[mcc];
  if (!entry) return mcc;
  return entry[langVal] ?? entry.en;
}
